assistant_id: 20260206-
language: en
version: "3.1"

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 3
    max_ngram: 5
  - name: DIETClassifier
    epochs: 80
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.35          
    ambiguity_threshold: 0.1

policies:
  - name: RulePolicy
    enable_fallback_prediction: true
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"

